Blog app: add devise
Kidd254/BlogApp pull request #10
Opened 2023-10-12 17:48 UTC by Kidd254

In this pull request I:
- [ ] Removed current_user method in ApplicationController, as devise will provide one.
    [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
- [ ] I made sure I :
1.         Can register a new user.
2.         User logs in with a combination of email and password.
3.         Hashed password should be stored in the database.
4.         Ask for confirmation of email.
5.         Can reset password.
- [ ]  [Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and your styling.

2023-10-12 18:33 UTC, Owusu-Desmond requested changes
Hi @Kidd254 and @mohashyne , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 18:33 UTC, Owusu-Desmond commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] Kindly ensure that you enabled `:confirmable` in the user model which should allow a sure to confirm the registration process below proceeding. You should see something similar to what is below: :point_down: 
  
  ```ruby
	  devise :database_authenticatable, :registerable,
				  :recoverable, :rememberable, :validatable, :confirmable
  ```

2023-10-12 19:32 UTC, Lucas-Masaba requested changes
# Hello @Kidd254  👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost-there](https://media.giphy.com/media/dEPGknRiEniec/giphy.gif)

 ## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 19:32 UTC, Lucas-Masaba commented on db/migrate/20231012142237_add_devise_to_users.rb
> +      # t.string   :unconfirmed_email # Only if using reconfirmable
- [ ] This should be uncommented and added to your schema for confirmable to work. `confirmed_at` is undefined and I get this error:
![image](https://github.com/Kidd254/BlogApp/assets/45460192/ec2886d6-db19-41d1-8565-88fa1c53b50e)
You should run your migrations with confirmable uncommented.

2023-10-13 13:46 UTC, mikethreels approved these changes
Hi Lawrence, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- good job implementing the requested changes.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-13 14:25 UTC, merged