Blog app - integration specs for views and fix n+1 problems
Kidd254/BlogApp pull request #9
Opened 2023-10-10 20:17 UTC by Kidd254

In this pull request we:

- [ ] Made sure that the N+1 problem is solved when fetching all posts and their comments for a user.
- [ ] before 
![Capture comments before](https://github.com/Kidd254/BlogApp/assets/106907574/79c1deee-f6bd-4a89-bc3e-3977c1582a5f)
![Capture before](https://github.com/Kidd254/BlogApp/assets/106907574/9526025a-ceb6-463d-8bc5-5161da72563c)

- [ ] After 
![Capture After](https://github.com/Kidd254/BlogApp/assets/106907574/2c35cb66-b432-48eb-bf39-377c7a462bf6)

- [ ] wrote integration tests for each view in your project

2023-10-11 08:09 UTC, rloterh requested changes
Hi Lawrence, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project, but you are almost there! 
🏁 🚦  ⛪ 🚜  🏃   🌴  🏫 🌳 🏘️ 

## Highlights 👍  
- N + 1 problem addressed!
- ReadMe looks great!

## Required Changes ♻️
_Kindly check the inline comments under the review._

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 08:09 UTC, rloterh commented on spec/features/post_index_spec.rb
> +end
- [ ] A test to assert the scenario **_I can see a section for pagination if there are more posts than fit on the view_** for _post index_ view integration spec is missing! Please ensure to improve upon this aspect.

2023-10-11 08:09 UTC, rloterh commented on spec/features/user_index_spec.rb
> +  end
- [ ] A number of integration spec test cases are failing. Let's ensure tests configurations are done properly and all spec tests are passing! 

Failing test cases:
![image](https://github.com/Kidd254/BlogApp/assets/12745474/ce9a19e2-4511-40de-8216-5ecc416a8af5)

2023-10-11 16:55 UTC, Gambit142 requested changes
Hi @Kidd254 @mohashyne 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- Setup linters properly ✔️ 
- Used `Rspec` as testing library ✔️ 
- Installed `capybara` gem ✔️
- Wrote feature tests for Users and Posts pages ✔️  
- Solved **_N+1 query_** problem ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 16:55 UTC, Gambit142 commented on spec/features/post_index_navigation_spec.rb
> +end
- [ ] Great work adding the missing test for navigation. However, some of the tests still fail. As highlighted by the previous reviewer, all tests need to pass because it gives a high level of confidence that your application functions properly. Please ensure that all tests pass.

![image](https://github.com/Kidd254/BlogApp/assets/77106962/cc83d270-70b5-44c7-892e-b449f543be04)

![image](https://github.com/Kidd254/BlogApp/assets/77106962/163b8410-e32d-4bed-953b-d4e80ce02575)

2023-10-11 21:12 UTC, Strangeal requested changes
Hi @Kidd254, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Alt Text](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 21:12 UTC, Strangeal commented on spec/features/post_index_navigation_spec.rb
> +end
- [ ] 👏 Great job on your test implementation effort! 👏

   - However, as highlighted by the previous reviewer, there are still some failing tests. 🧐 It's essential to ensure that all tests pass, as this not only demonstrates the functionality of your application but also boosts your confidence in its proper operation. Below is a screenshot of your test fails:
   
<img width="1185" alt="Screenshot 2023-10-11 at 21 01 54" src="https://github.com/Kidd254/BlogApp/assets/107192076/76c3b7ee-35b4-472f-b6c9-cff2621f0d77">


🚀 Keep up the good work! 👍😊

2023-10-12 09:58 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @Kidd254, 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Great effort implementing the changes 🔥 
✅ Good commit messages 👍 


## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 10:07 UTC, merged